const colors = {
  light: {
    text: "#1A1F2E",
    tint: "#0070F3",
    background: "#F5F7FA",
    foreground: "#1A1F2E",
    card: "#FFFFFF",
    cardForeground: "#1A1F2E",
    primary: "#0070F3",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2F8",
    secondaryForeground: "#1A1F2E",
    muted: "#EEF2F8",
    mutedForeground: "#6B7280",
    accent: "#4B7CF6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E9F0",
    input: "#E8ECF4",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00C781",
    background: "#0A0B0E",
    foreground: "#FFFFFF",
    card: "#111318",
    cardForeground: "#FFFFFF",
    primary: "#00C781",
    primaryForeground: "#000000",
    secondary: "#1A1E26",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1E26",
    mutedForeground: "#7A8394",
    accent: "#4B7CF6",
    accentForeground: "#FFFFFF",
    destructive: "#E8333A",
    destructiveForeground: "#FFFFFF",
    border: "#242830",
    input: "#1A1E26",
  },
  radius: 14,
};

export default colors;
